// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9MH4NjYetbB78mLxREuzqjVg7BvuIXDE',
    appId: '1:33592492352:web:8cc651a5efdb234ef47aa5',
    messagingSenderId: '33592492352',
    projectId: 'muict-connect-75869',
    authDomain: 'muict-connect-75869.firebaseapp.com',
    storageBucket: 'muict-connect-75869.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYfgF_nsxgiQqoAV7eL78kBe4i_eqzxlc',
    appId: '1:33592492352:android:5c865453eb117b9ef47aa5',
    messagingSenderId: '33592492352',
    projectId: 'muict-connect-75869',
    storageBucket: 'muict-connect-75869.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY8CDNcQwmvo9U99BsrC_Txzm9Hw-VMBk',
    appId: '1:33592492352:ios:ec7da0ee3f624925f47aa5',
    messagingSenderId: '33592492352',
    projectId: 'muict-connect-75869',
    storageBucket: 'muict-connect-75869.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCY8CDNcQwmvo9U99BsrC_Txzm9Hw-VMBk',
    appId: '1:33592492352:ios:caf6324b82e086bcf47aa5',
    messagingSenderId: '33592492352',
    projectId: 'muict-connect-75869',
    storageBucket: 'muict-connect-75869.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
